version: 0.0
os: linux
files:
    - source: /
      destination: /home/ubuntu/api
permissions:
    - object: /home/ubuntu
      owner: ubuntu
      group: ubuntu
      type:
          - directory
          - file
hooks:
    BeforeInstall:
        - location: scripts/cd/BeforeInstall.sh
          timeout: 300
          runas: root
    AfterInstall:
        - location: scripts/cd/AfterInstall.sh
          timeout: 300
          runas: root
    ApplicationStart:
        - location: scripts/cd/ApplicationStart.sh
          timeout: 300
          runas: root
    ApplicationStop:
        - location: scripts/cd/ApplicationStop.sh
          timeout: 300
          runas: root
