version: '3.5'

services:
    api_ci:
        container_name: thx_api_ci
        build:
            context: .
            target: develop
        env_file: .env.ci
        ports:
            - 3002:3001
        depends_on:
            - api_ci_mongo
            - api_ci_mainnet
        networks:
            - thx_ci_network

    api_ci_mongo:
        container_name: thx_api_ci_mongo
        image: mongo
        env_file: .env.ci
        networks:
            - thx_ci_network
        ports:
            - 27018:27017
        environment:
            MONGO_INITDB_ROOT_USERNAME: root
            MONGO_INITDB_ROOT_PASSWORD: root
            MONGO_INITDB_DATABASE: admin
            DB_NAME: $MONGODB_NAME
            DB_USER: $MONGODB_USER
            DB_PASSWORD: $MONGODB_PASSWORD

    api_ci_mainnet:
        container_name: thx_api_ci_mainnet
        image: trufflesuite/ganache:v7.0.2
        networks:
            - thx_ci_network
        ports:
            - '8549:8545'
        command:
            [
                "--account='0x873c254263b17925b686f971d7724267710895f1585bb0533db8e693a2af32ff,100000000000000000000'",
                "--account='0x5a05e38394194379795422d2e8c1d33e90033d90defec4880174c39198f707e3,100000000000000000000'",
                "--hardfork='london'",
                '-l 25000000',
            ]

networks:
    thx_ci_network:
        name: thx_ci_network
