name: CI

on:
    pull_request:
        branches:
            - develop

jobs:
    buildAndTest:
        name: CI Pipeline
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: ['12.x']

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Install Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}

            - name: Start containers
              run: docker compose -f docker-compose.ci.yml up -d

            - name: Install dependencies
              run: npm install

            - name: Run test
              run: npm run test
